host = "127.0.0.1"
port = 8100
geofence_path = "geofences"
uicon_url = "https://raw.githubusercontent.com/whitewillem/PogoAssets/main/uicons/"


[[area]]
name = "GLOBAL"
webhooks = [
    "https://discord.com/api/webhooks/1",
    "https://discord.com/api/webhooks/2"
]

[[area]]
name = "test"
webhooks = [
    "https://discord.com/api/webhooks/1"
]
# You can define as many areas and webhooks as you want following the example format.
# The name has to match a Geofence name of your Geofence directory. "GLOBAL" is a wildcard and lets through everything
