host = "127.0.0.1"
port = 8100
uicon_url = "https://raw.githubusercontent.com/whitewillem/PogoAssets/main/uicons/"

discord_webhooks = [
    "https://discord.com/api/webhooks/1",
    "https://discord.com/api/webhooks/2"
]